from enum import Enum


class Category(str, Enum):
    Sport = "Sport"
    Politics = "Politics"
    Technology = "Technology"
    Entertainment = "Entertainment"
    Business = "Business"
    Health = "Health"
    Science = "Science"
    World = "World"
    Education = "Education"
    Environment = "Environment"
    Weather = "Weather"
    Economy = "Economy"
    Society = "Society"
    Culture = "Culture"
    Lifestyle = "Lifestyle"
    Opinion = "Opinion"
    Religion = "Religion"
    History = "History"
    Food = "Food"
    Fashion = "Fashion"
    Travel = "Travel"
    Music = "Music"
    Movies = "Movies"
    Television = "Television"
    Books = "Books"
    Art = "Art"
    Theater = "Theater"
    Dance = "Dance"
    Photography = "Photography"
